#!/usr/bin/env python3
"""Regenerate src/inferno_lut.h: OpenCV's 256-entry INFERNO colormap as RGB.

The on-screen depth view (src/depthview.cpp) colorizes depth with this table
so it matches tools/ringdump.py, which uses cv2.COLORMAP_INFERNO directly.

    ../bat-tim/.venv/bin/python tools/gen_inferno_lut.py > src/inferno_lut.h
"""

import cv2
import numpy as np

ramp = np.arange(256, dtype=np.uint8).reshape(1, 256)
bgr = cv2.applyColorMap(ramp, cv2.COLORMAP_INFERNO)[0]  # (256, 3) B,G,R

print("// Generated by tools/gen_inferno_lut.py -- do not edit by hand.")
print("// cv2.COLORMAP_INFERNO as R,G,B triplets; index 0 = far, 255 = near.")
print("#ifndef BATHAT_INFERNO_LUT_H")
print("#define BATHAT_INFERNO_LUT_H")
print()
print("#include <cstdint>")
print()
print("static const uint8_t kInfernoRgb[256][3] = {")
for i in range(0, 256, 4):
    row = "    " + " ".join("{%3d, %3d, %3d}," % (b[2], b[1], b[0])
                            for b in bgr[i:i + 4])
    print(row)
print("};")
print()
print("#endif  // BATHAT_INFERNO_LUT_H")
